### ISSUE TITLE
Can't add more that 42 products on an attachment.

### ISSUE THREAD

**Issue by Jim360** [mageprince/magento2-productAttachment#34] opened 2018-06-20 21:43 UTC
Can't add more that 42 products on an attachment in Magento 2.2.3. When I try to add more products, it will save without error but when I look at the attachment record the newly added product is not there.

Already using the current version. Setup/InstallSchema.php
![prod_attach](https://user-images.githubusercontent.com/40399221/41686251-ff162518-74a8-11e8-95b9-92aa61b2a6cd.PNG)

**Comment by Jim360** [comment] 2018-06-21 19:49
I fixed this issue by manually updating the "product" column for "prince_productattach" table. I was previously using an older version of this module and found out that the database schema was not updated even after fully disabling and deleting the module then reinstalling the updated version of it which supposedly contains the fix for this issue. Its all good now.

**Comment by unicoder88** [comment] 2018-06-22 06:09
Hey, I've been watching this thread. Yes, install script is run only for new installations, a better way would be to introduce upgrade script to migrate existing module users. For now manually changing column type is the only way to update.

**Comment by mageprince** [comment] 2018-06-23 05:00
Closed as duplicate of #19

**Closed as completed by mageprince** 2018-06-23 05:00 UTC
Labels: duplicate
