### ISSUE TITLE
Katalog->Manage Attachments generates error

### ISSUE THREAD

**Issue by Maenz** [mageprince/magento2-productAttachment#64] opened 2019-11-18 13:57 UTC
Hello!

Thank you for your great extension! After installing on my Magento 2.3.3 with PHP 7.2.22 I want to manage my attachments but I got the following error message:

{"0":"Class argument is invalid: Magento\\Framework\\View\\Element\\UiComponent\\Context","1":"<pre>#1 Magento\\Framework\\Data\\Argument\\InterpreterInterface\\Proxy->evaluate() called at [vendor\/magento\/framework\/Data\/Argument\/Interpreter\/Composite.php:61]\n#2 Magento\\Framework\\Data\\Argument\\Interpreter\\Composite->evaluate() called at [vendor\/magento\/module-ui\/Config\/Data.php:164]\n#3 Magento\\Ui\\Config\\Data->evaluateComponentArguments() called at [vendor\/magento\/module-ui\/Config\/Data.php:111]\n#4 Magento\\Ui\\Config\\Data->initData() called at [vendor\/magento\/module-ui\/Config\/Data.php:136]\n#5 Magento\\Ui\\Config\\Data->get() called at [vendor\/magento\/framework\/View\/Layout\/Reader\/UiComponent.php:100]\n#6 Magento\\Framework\\View\\Layout\\Reader\\UiComponent->interpret() called at [vendor\/magento\/framework\/View\/Layout\/ReaderPool.php:105]\n#7 Magento\\Framework\\View\\Layout\\ReaderPool->interpret() called at [vendor\/magento\/framework\/View\/Layout\/Reader\/Container.php:89]\n#8 Magento\\Framework\\View\\Layout\\Reader\\Container->interpret() called at [vendor\/magento\/framework\/View\/Layout\/ReaderPool.php:105]\n#9 Magento\\Framework\\View\\Layout\\ReaderPool->interpret() called at [vendor\/magento\/framework\/View\/Page\/Config\/Reader\/Body.php:68]\n#10 Magento\\Framework\\View\\Page\\Config\\Reader\\Body->interpret() called at [vendor\/magento\/framework\/View\/Layout\/ReaderPool.php:105]\n#11 Magento\\Framework\\View\\Layout\\ReaderPool->interpret() called at [vendor\/magento\/framework\/View\/Layout.php:325]\n#12 Magento\\Framework\\View\\Layout->generateElements() called at [generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php:89]\n#13 Magento\\Framework\\View\\Layout\\Interceptor->generateElements() called at [vendor\/magento\/framework\/View\/Layout\/Builder.php:129]\n#14 Magento\\Framework\\View\\Layout\\Builder->generateLayoutBlocks() called at [vendor\/magento\/framework\/View\/Page\/Builder.php:55]\n#15 Magento\\Framework\\View\\Page\\Builder->generateLayoutBlocks() called at [vendor\/magento\/framework\/View\/Layout\/Builder.php:65]\n#16 Magento\\Framework\\View\\Layout\\Builder->build() called at [vendor\/magento\/framework\/View\/Layout.php:253]\n#17 Magento\\Framework\\View\\Layout->build() called at [vendor\/magento\/framework\/View\/Layout.php:875]\n#18 Magento\\Framework\\View\\Layout->getBlock() called at [generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php:414]\n#19 Magento\\Framework\\View\\Layout\\Interceptor->getBlock() called at [vendor\/magento\/module-backend\/Model\/View\/Result\/Page.php:26]\n#20 Magento\\Backend\\Model\\View\\Result\\Page->setActiveMenu() called at [generated\/code\/Magento\/Backend\/Model\/View\/Result\/Page\/Interceptor.php:24]\n#21 Magento\\Backend\\Model\\View\\Result\\Page\\Interceptor->setActiveMenu() called at [vendor\/prince\/module-productattachment\/Controller\/Adminhtml\/Index\/Index.php:77]\n#22 Prince\\Productattach\\Controller\\Adminhtml\\Index\\Index->execute() called at [generated\/code\/Prince\/Productattach\/Controller\/Adminhtml\/Index\/Index\/Interceptor.php:37]\n#23 Prince\\Productattach\\Controller\\Adminhtml\\Index\\Index\\Interceptor->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]\n#24 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:231]\n#25 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#26 Prince\\Productattach\\Controller\\Adminhtml\\Index\\Index\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#27 Prince\\Productattach\\Controller\\Adminhtml\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:143]\n#28 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#29 Prince\\Productattach\\Controller\\Adminhtml\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#30 Prince\\Productattach\\Controller\\Adminhtml\\Index\\Index\\Interceptor->___callPlugins() called at [generated\/code\/Prince\/Productattach\/Controller\/Adminhtml\/Index\/Index\/Interceptor.php:52]\n#31 Prince\\Productattach\\Controller\\Adminhtml\\Index\\Index\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:159]\n#32 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:99]\n#33 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#34 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#35 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#36 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#37 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:137]\n#38 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:24]\n#39 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]\n#40 Magento\\Framework\\App\\Bootstrap->run() called at [index.php:39]\n<\/pre>","url":"\/admin\/productattach\/index\/index\/key\/f87a5d82f29439cd7e6fba1a4de06a8eb2079e59d567e5985eea16b87a7c4fdb\/","script_name":"\/index.php"}

**Comment by mageprince** [comment] 2019-11-20 09:43
@Maenz Please check the solution on issue #63 
Duplicate of issue #63

**Closed as completed by mageprince** 2019-11-20 09:43 UTC
